name: "Build"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Nix
        if: success()
        uses: cachix/install-nix-action@v16
        # with:
        #   install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        #   extra_nix_config: |
        #     experimental-features = nix-command flakes
      - name: Build
        if: success()
        run: nix build
